---
- name: creating EC2 with ansible
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False

  vars:
    instance_type: t2.micro
    security_group: launch-wizard-1
    image: ami-0d8f6eb4f641ef691
    region: us-east-2
    keypair: ohio
    count: 1

  tasks:
    - name: build EC2
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for Newly Created EC2 Instance
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0


    - name: Launch the new t2 micro EC2 Instance
      local_action: ec2
        group={{ security_group }}
        instance_type={{ instance_type}}
        image={{ image }}
        wait=true
        region={{ region }}
        keypair={{ keypair }}
        count={{count}}

      register: ec2

    - name: Wait for EC2 Instance to Spin-up and ready for SSH access
      local_action: wait_for
        host={{ item.public_ip }}
        port=22
        state=started
      with_items: "{{ ec2.instances }}"

    - name: Adding Tags to Identify
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: slave
          Owner: maggie
          #version number or jenkins number put here.  jenkins number or some ways to keep track of deployment.  do another ec2 gather facts.
          PurPose: provision ec2 then connect and do stuff
    
    - name: see whats the file like.  i want to store the instances.id somewhere for later use.  
      command: pwd

    - name: Stop or terminate myserver instance
      local_action:
        module: ec2
        region: "us-east-1"
        instance_ids: "{{ item.id }}"
        state: stopped
      with_items: "{{ ec2.instances}}"
